import { PARQUET_ATTR_TO_CODE, REVERSE_QUARTER_MAP } from './constants.js';

export class CourseService {
    /**
     * Pure function to format a single section object. 
     * Shared across both standard and unified display modes.
     */
    static shapeSection(sec) {
        const s = { ...sec }; 
        s.restrictions = s.restrictions ? { ...s.restrictions } : {};
        s.attributes = s.attributes ? { ...s.attributes } : {};
        
        const badges = [];
        for (const [attrKey, code] of Object.entries(PARQUET_ATTR_TO_CODE)) {
            if (s.attributes[attrKey]) badges.push(code);
        }
        s.ui_badges = badges;

        s.ui_short_id = s.section_id.split('-').pop();
        s.ui_credits = s.credits_min !== null 
            ? (s.credits_min === s.credits_max ? `${s.credits_min}` : `${s.credits_min}-${s.credits_max}`) 
            : "";

        const rawMeetings = s.meetings ? [...s.meetings] : [];
        s.meetings = rawMeetings.map(mtg => {
            const m = { ...mtg };
            m.time = m.time ? { ...m.time } : {};
            m.time.days = m.time.days ? [...m.time.days] : [];
            
            const start = m.time.start_time || '';
            const end = m.time.end_time || '';
            
            m.ui_days = m.time.days.join('');
            m.ui_time = (start && end) ? `${start}-${end}` : (start || '');
            
            return m;
        });

        return s;
    }

    /**
     * Unseals standard flat Apache Arrow Proxies and shapes the nested structures
     */
    static shapeDataForUI(rows) {
        return rows.map(row => {
            const course = { ...row }; 

            const termCode = Number(course.term_code);
            course.ui_year = Math.floor(termCode / 10);
            course.ui_quarter = REVERSE_QUARTER_MAP[termCode % 10] || 'UNK';

            course.gen_ed_reqs = course.gen_ed_reqs ? [...course.gen_ed_reqs] : [];
            
            // Unseal Apache Arrow proxy into JS array
            const rawSections = course.sections ? [...course.sections] : [];

            course.sections = rawSections.map(sec => this.shapeSection(sec));

            return course;
        });
    }

    /**
     * Folds flat rows generated by DENSE_RANK into a grouped Unified structure
     */
    static shapeUnifiedDataForUI(rows) {
        const courseMap = new Map();

        // 1. Iterate over flat rows and fold them into our map
        rows.forEach(row => {
            const courseKey = `${row.course_prefix}-${row.course_number}`;
            
            // Create the parent course object if we haven't seen this prefix+number yet
            if (!courseMap.has(courseKey)) {
                courseMap.set(courseKey, {
                    course_prefix: row.course_prefix,
                    course_number: row.course_number,
                    course_title: row.course_title,
                    // has_prerequisites: row.has_prerequisites,
                    // gen_ed_reqs: row.gen_ed_reqs ? [...row.gen_ed_reqs] : [],
                    // notes: row.notes,
                    terms: []
                });
            }

            const course = courseMap.get(courseKey);
            
            // Process the specific term's data for this row
            const termCode = Number(row.term_code);
            const ui_year = Math.floor(termCode / 10);
            const ui_quarter = REVERSE_QUARTER_MAP[termCode % 10] || 'UNK';
            
            const rawSections = row.sections ? [...row.sections] : [];

            course.terms.push({
                termCode: termCode,
                ui_year: ui_year,
                ui_quarter: ui_quarter,
                formatted_quarter: `${ui_quarter} ${ui_year}`,
                has_prerequisites: row.has_prerequisites,                       // Moved here
                gen_ed_reqs: row.gen_ed_reqs ? [...row.gen_ed_reqs] : [],       // Moved here
                notes: row.notes,                                               // Moved here
                sections: rawSections.map(sec => this.shapeSection(sec))
            });
        });

        // 2. Convert Map back to an array
        const unifiedCourses = Array.from(courseMap.values());
        
        // 3. Ensure the terms inside each course are sorted newest-first
        unifiedCourses.forEach(course => {
            course.terms.sort((a, b) => b.termCode - a.termCode);
        });

        return unifiedCourses;
    }
}